server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: bronze-eureka

