spring:
  application:
    name: bronze-product-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: e10adc3949ba59abbe56e057f20f883e
    url: jdbc:mysql://192.168.19.134:3308/shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080